Dp 781
pepfar-datim/datimutils pull request #110
Opened 2022-09-06 12:18 UTC by flopez-bao

- Since `getDataValueSets`  has been deprecated from `datapackr`, `datimutils::getDataValueSets` was altered to allow passing only a `dataElementGroup` as well as an `orgUnitGroup`
- Now it will require missing both data or org elements to kick the stop error

2022-09-07 10:51 UTC, sam-bao requested changes
In addition to updating the two error messages, please look at the coverage report. It looks like we do not have unit tests which take us into all of the error handling paths.

2022-09-07 10:51 UTC, sam-bao commented on R/getDataValueSets.R
>      stop("At least one data set must be specified.")
Please update the error message as it currently only references data set

2022-09-07 10:51 UTC, sam-bao commented on R/getDataValueSets.R
>      stop("At least one organisation unit must be specified.")
Nice catch that org unit groups are a similar situation, please update the error message as it only references organisation unit

2022-09-07 13:20 UTC, flopez-bao commented
@sam-bao , updated the error messages to include the new condition and updated testing to cover both messages. Let me know if this suffices.

2022-09-08 11:44 UTC, sam-bao approved these changes

2022-09-08 11:50 UTC, merged