APD 1894
pepfar-datim/datimutils pull request #113
Opened 2022-10-21 17:02 UTC by JordanBalesBAO

Created documentation and an example shiny app. This is to provide the pdap client's assistance with applying OAuth to their shiny applications

2022-10-21 17:44 UTC, JordanBalesBAO commented
@sam-bao how do the end users launch the vignette?  

Neither vignette(package = "datimutils") or browseVignettes("datimutils") return anything for me. I also tried to devtools install with build_vignettes = TRUE, but that errored out as well.

2022-10-24 17:42 UTC, flopez-bao approved these changes
looks good to me, this should be sufficient to add oauth.

2022-10-25 11:36 UTC, sam-bao requested changes
Review error I am receiving and if required patch the code.

2022-10-25 11:36 UTC, sam-bao commented on inst/shiny-examples/OAuth/server.R
> +            credentials = httr::oauth2.0_access_token(endpoint = oauth_api,
@JordanBalesBAO I am erroring out at this point in the code (I think). I made what I believe are the necessary parameter changes and do make it to Datim and back.

![image](https://user-images.githubusercontent.com/36417685/197762949-9d72f409-375f-4ebf-9a13-aed536a06324.png)

But on the console I am seeing.
```
Warning: Error in httr::oauth2.0_access_token: Bad Request (HTTP 400). Failed to get an access token.
```

@flopez-bao did you try to run through the example or did you just do a code review?

2022-10-26 16:59 UTC, JordanBalesBAO commented on inst/shiny-examples/OAuth/server.R
> +            credentials = httr::oauth2.0_access_token(endpoint = oauth_api,
I actually believe it was related to how the port was being set. Since we are using a multi file shiny app the order of execution is different than a single app.R file I have used in the past. I pushed an update that contains a comment explaining.

That being said I generally have only gotten a 400 error when the OAuth2 client on DHIS2 is configured incorrectly.

2022-10-26 17:08 UTC, flopez-bao commented on inst/shiny-examples/OAuth/server.R
> +            credentials = httr::oauth2.0_access_token(endpoint = oauth_api,
<img width="1350" alt="Screen Shot 2022-10-26 at 1 08 18 PM" src="https://user-images.githubusercontent.com/92821116/198091475-1745bdbc-7679-47c1-81cb-680b4d079221.png">
Works for me @sam-bao

2022-11-01 11:06 UTC, sam-bao approved these changes
This works so I see no reason to block adding it to the package. But I can't help but feel this example and perhaps the OAUTH functions in datimutils are more complex than it should be.

I don't think a developer should need to call `httr` from their shiny app, all the `httr` complexity should be part of the oauth login support from datimutils. Also, I think if I was building a shiny app I would use the `d2_session_envir` option to land the `d2_default_session` session in the server environment. Then I could make datimutils calls without explicitly passing the session object. I believe this can be accomplished by determining the server environment at the beginning of the server function
```
shinyServer(function(input, output, session) {
server_env = environment()
    validation_results <- reactive({ validate() }) # nolint

    ready <- reactiveValues(ok = FALSE)

    user_input <- reactiveValues(authenti
```

And then passing server_env variable to the login function

``` datimutils::loginToDATIMOAuth(base_url =  "https://cop-test.datim.org/",
                                          token = token,
                                          app = oauth_app,
                                          api = oauth_api,
                                          redirect_uri = APP_URL,
                                          scope = oauth_scope,
                                          d2_session_envir = server_env
            ) }
```
No reactive variables or R6 object cloning required for the session.

2022-11-01 15:39 UTC, merged