add getPSNUS file
pepfar-datim/datimutils pull request #59
Opened 2020-08-28 19:05 UTC by maxwellchandler

2020-10-02 11:28 UTC, sam-bao commented
@maxwellchandler I am not getting back what I expect when I run:

```
devtools::install_github("pepfar-datim/datimutils", 
                         "gh450",
                         upgrade = c("never"))

library(datimutils)
library(magrittr)
library(tidyverse)

loginToDATIM("~/.secrets/datim.json")

ous <- getOrgUnits(c("Rwanda", "South Africa", "West Africa Region"), by = "name")

getPSNUs(ous)
```

I expect a data frame with a single list column and three rows, but I get back:

```
[1] "https://www.datim.org/api/organisationUnitGroups.json?paging=false&filter=id:in:[AVy8gJXym2D]&fields=id,organisationUnits[name,id,ancestors[id],name"
[1] name      id        ancestors
<0 rows> (or 0-length row.names)
```

2020-10-03 20:56 UTC, maxwellchandler commented
@sam-bao Sam, i have fixed a few things here, but the principal problem is that those three uids are not in the list of psnus.

2020-10-05 08:21 UTC, sam-bao commented
@maxwellchandler getPSNUs should return all PSNUs at or below the org units provided in the org hierarchy.

So, `getPSNUs(south_africa_uid)` would return all PSNUs in South africa, and `getPSNUs(c(south_africa_uid,rwanda_uid))` should return a data frame with two rows and one list column in the first row the psnu ids for South Africa, in the second row the PSNU ids for Rwanda.

I think the easiest, best performing way to do this is to get the list of all PSNUs including `path` in the fields returned from the API and then from within R do a text search comparing paths with the input uids.

2020-10-05 10:08 UTC, sam-bao requested changes

2020-10-05 10:08 UTC, sam-bao commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
@maxwellchandler What is this new parameter for?

2020-10-05 15:26 UTC, maxwellchandler commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
Because getOrgunits (and all the other helpers), pass in name and id in the fields section if it isnt there, but in thin case we dont want that, it messes with the string manipulation done to create organisationUnits[name,id,ancestors[id]]

2020-10-05 15:52 UTC, sam-bao commented
@maxwellchandler I see. I think that getPSNUs, should explicitly request the fields it needs when calling getOrgUnitGroups rather than rely on the default fields. 

e.g.

```
ancestor_uids = c(country_uid1, country_uid2)
fields = "id"
getPSNUs(ancestor_uids, fields = fields)
```

would call `getOrgUnitGroups("AVy8gJXym2D", fields = "organisationUnits[id,path]")` where path is added to allow filtering PSNUs by the ancestors.

getOrgUnitGroups should return to getPSNUs a list of the uids and paths for all org units in the PSNU org unit group.

Then getPSNUs would filter the results from the getOrgUnitGroups returned object for each ancestor_uid. `getPSNUs` should only return path if it was requested in the `getPSNUs` fields parameter.

2020-10-05 15:52 UTC, sam-bao commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
@maxwellchandler I see. I think that getPSNUs, should explicitly request the fields it needs when calling getOrgUnitGroups rather than rely on the default fields.

e.g.

ancestor_uids = c(country_uid1, country_uid2)
fields = "id"
getPSNUs(ancestor_uids, fields = fields)
would call getOrgUnitGroups("AVy8gJXym2D", fields = "organisationUnits[id,path]") where path is added to allow filtering PSNUs by the ancestors.

getOrgUnitGroups should return to getPSNUs a list of the uids and paths for all org units in the PSNU org unit group.

Then getPSNUs would filter the results from the getOrgUnitGroups returned object for each ancestor_uid. getPSNUs should only return path if it was requested in the getPSNUs fields parameter.

2020-10-06 08:33 UTC, sam-bao commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
```
devtools::install_github("pepfar-datim/datimutils", 
                         "gh450",
                         upgrade = c("never"))

library(datimutils)
library(magrittr)
library(tidyverse)

loginToDATIM("~/.secrets/datim.json")

ous <- getOrgUnits(c("Rwanda", "South Africa", "West Africa Region"), by = "name")

getPSNUs(ous,fields="id") 
```

@maxwellchandler I am just getting a vector retunred instead of a data frame with three rows and on column, one row for each ou requested.

2020-10-06 08:35 UTC, sam-bao commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
Also I receive an error if I run this:
```
library(datimutils)
library(magrittr)
library(tidyverse)

loginToDATIM("~/.secrets/datim.json")

ous <- getOrgUnits(c("Rwanda", "South Africa", "West Africa Region"), by = "name")

getPSNUs(ous,fields="id,path") 
```

```
 Error in `[.data.frame`(psnus, , to_subset) : undefined columns selected
```

2020-10-06 12:34 UTC, maxwellchandler commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
@sam-bao I must have totally misunderstood our call yesterday because i thought thats what you wanted. "Only return fields that are specified", so in this case only return ID, and only return where rows have a uid in the path column.

2020-10-06 12:35 UTC, maxwellchandler commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
@sam-bao As far as the other bug, if you do c("id","path") will work

2020-10-06 12:47 UTC, maxwellchandler commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
@sam-bao I just pushed a fix where single frame data frames dont drop to vector

2020-10-13 11:24 UTC, sam-bao requested changes

2020-10-13 11:50 UTC, sam-bao commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
@maxwellchandler getPSNUs is still not returning what I am looking for

```
library(datimutils)
library(magrittr)
library(tidyverse)

loginToDATIM("~/.secrets/datim.json")

ous <- getOrgUnits(c("Rwanda", "South Africa", "West Africa Region"), by = "name")

getPSNUs(ous,fields="id,path") 
```

I should get back data frame with three rows and one list column. there should be one row for each country ordered the same as the input list. The column should be a list column. each row of the list column should be a data frame of the organisation unit fields requests for the country. 

```
devtools::install_github("pepfar-datim/datimutils", 
                         "gh450",
                         upgrade = c("never"))

library(datimutils)
library(magrittr)
library(tidyverse)

loginToDATIM("~/.secrets/datim.json")

ous <- getOrgUnits(c("Rwanda", "South Africa", "West Africa Region"), by = "name")


psnus <- getOrgUnitGroups("AVy8gJXym2D", fields = "organisationUnits[id,path]")

return <- purrr::map(ous, ~dplyr::filter(psnus,
                               stringr::str_detect(path, .x)) %>% 
                                 dplyr::select(id))

```

2020-10-13 12:08 UTC, sam-bao commented on R/getMetadataEndpoint.R
> +#' @param modify_fields whether or not to modify fields or use exactly what is passed in
I just noticed my examples aren't quite right as the contents of return in my examples above are lists rather than data frames. I will create correct examples later today.

2020-10-14 01:23 UTC, maxwellchandler commented on R/getPSNUS.R
> +  if(!(is.null(uids))){
@sam-bao Should all be good now

`ous <- getOrgUnits(c("Rwanda", "South Africa", "West Africa Region"), by = "name")
see <- getPSNUs(ous, fields = c("id","name", "path"))
see$psnus[[1]]`

2020-10-19 13:15 UTC, sam-bao requested changes

2020-10-19 13:15 UTC, sam-bao commented on R/getPSNUS.R
> +    column_name <- "countries"
@maxwellchandler let's keep the renaming part in the other functions getPSNUs, .... I would like `.getOrgUnitsByOrgUnitGroup` to be independent of DATIM, so we can unit test this function against play.dhis2.org. The Rest of the functions are such thin wrappers over `.getOrgUnitsByOrgUnitGroup` that I am not to concerned with them being covered by unit test.

2020-10-20 00:06 UTC, maxwellchandler commented on R/getPSNUS.R
> +    column_name <- "countries"
@sam-bao Ok, no problem, its done

2022-07-22 14:36 UTC, cnemarich commented
Isolated these changes into PR #101.

2022-07-22 14:36 UTC, closed without merging